### ISSUE TITLE
Autoclicker

### ISSUE THREAD

**Issue by THEBEST1278** [Browncha023/avo-ultimate#2]
when I put the auto clicker in the folder I put javascript: in front of the code and it worked cuz when I clicked on it showed the way to turn it on and change the key bind but it never actually turns the actual auto clicker on. Is it because I'm on a Chromebook or is it just an overall issue?

**Comment by Browncha023** [comment]
So... their is only one bookmarklet, the one in the readme. The autoclicker runs through that, though the autoclicker is not currently viewable just because the jsdelivr link needs to update(I opened an issue for it, but it should be fixed in less than 24 hours). Once it does, it should work through that (it did work in my beta testing). If it doesn't work then, you can reopen the issue.

**Comment by THEBEST1278** [comment]
ok Thx :) 👍
